import { supabase } from '../lib/supabase';
import { guardCompanyId } from '../lib/tenantGuard';

// Get all assets — MANDATORY company scope
export async function getAllAssets(companyId) {
  if (!guardCompanyId(companyId, 'getAllAssets')) return { data: [], error: null };
  const { data, error } = await supabase
    .from('assets')
    .select('*, employees:assigned_to(name, division)')
    .eq('company_id', companyId)
    .order('created_at', { ascending: false });
  return { data: data || [], error };
}

// Get asset by ID
export async function getAssetById(id) {
  const { data, error } = await supabase
    .from('assets')
    .select('*, employees:assigned_to(name, division)')
    .eq('id', id)
    .single();
  return { data, error };
}

// Create asset — REMOVED client-controlled id (let DB auto-generate)
export async function createAsset(asset) {
  const { data, error } = await supabase
    .from('assets')
    .insert({
      // id is NOT accepted from client — auto-generated by database
      name: asset.name,
      category: asset.category,
      brand: asset.brand,
      serial: asset.serial,
      purchase_date: asset.purchaseDate,
      status: asset.status || 'available',
      assigned_to: asset.assignedTo || null,
      condition: asset.condition || 'Good',
      notes: asset.notes,
      company_id: asset.companyId || null,
    })
    .select()
    .single();
  return { data, error };
}

// Update asset — verify company ownership
export async function updateAsset(id, asset, companyId) {
  let query = supabase
    .from('assets')
    .update({
      name: asset.name,
      category: asset.category,
      brand: asset.brand,
      serial: asset.serial,
      purchase_date: asset.purchaseDate,
      status: asset.status,
      assigned_to: asset.assignedTo,
      condition: asset.condition,
      notes: asset.notes,
    })
    .eq('id', id);
  if (companyId) query = query.eq('company_id', companyId);
  const { data, error } = await query.select().single();
  return { data, error };
}

// Delete asset — verify company ownership
export async function deleteAsset(id, companyId) {
  let query = supabase.from('assets').delete().eq('id', id);
  if (companyId) query = query.eq('company_id', companyId);
  const { error } = await query;
  return { error };
}

// Assign asset to employee
export async function assignAsset(assetId, employeeId) {
  const { data, error } = await supabase
    .from('assets')
    .update({ assigned_to: employeeId, status: 'in-use' })
    .eq('id', assetId)
    .select()
    .single();
  return { data, error };
}

// Unassign asset
export async function unassignAsset(assetId) {
  const { data, error } = await supabase
    .from('assets')
    .update({ assigned_to: null, status: 'available' })
    .eq('id', assetId)
    .select()
    .single();
  return { data, error };
}
